# Generated by Django 4.2.6 on 2023-10-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0025_remove_carrinho_produto_carrinho_produto'),
        ('usuario', '0004_remove_usuario_carrinhos_remove_usuario_enderecos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carrinhos',
            field=models.ManyToManyField(blank=True, default=None, to='padaria.carrinho'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='enderecos',
            field=models.ManyToManyField(blank=True, default=None, to='padaria.endereco'),
        ),
    ]
