# Generated by Django 4.2.6 on 2023-11-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_usuario_carrinhos_usuario_carrinhos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='carrinhos',
            new_name='carrinho',
        ),
    ]
