# Generated by Django 4.2.6 on 2023-12-03 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0035_alter_item_produto'),
        ('usuario', '0007_rename_carrinhos_usuario_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carrinho',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='padaria.carrinho'),
        ),
    ]
