# Generated by Django 4.2.6 on 2023-12-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0035_alter_item_produto'),
        ('usuario', '0009_alter_usuario_enderecos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='enderecos',
            field=models.ManyToManyField(blank=True, default=None, to='padaria.endereco'),
        ),
    ]
