# Generated by Django 4.2.6 on 2023-12-07 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0035_alter_item_produto'),
        ('usuario', '0010_alter_usuario_enderecos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='enderecos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='enderecos',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='padaria.endereco'),
        ),
    ]
