# Generated by Django 4.2.6 on 2023-12-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_remove_usuario_enderecos_usuario_enderecos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='enderecos',
            new_name='endereco_usuario',
        ),
    ]
