# Generated by Django 4.2.6 on 2023-12-07 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0038_alter_carrinho_item'),
        ('usuario', '0012_rename_enderecos_usuario_endereco_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carrinho',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='padaria.carrinho'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco_usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='padaria.endereco'),
        ),
    ]
