# Generated by Django 4.2.2 on 2023-07-31 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0002_carrinho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinho',
            options={'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinhos'},
        ),
    ]
