# Generated by Django 4.2.2 on 2023-07-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0003_alter_carrinho_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='cep',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='numero',
            field=models.FloatField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='rua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
