# Generated by Django 4.2.2 on 2023-08-23 17:31

from django.db import migrations, models
import padaria.models.produto


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0005_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=1, upload_to=padaria.models.produto.image_file_path),
            preserve_default=False,
        ),
    ]
