# Generated by Django 4.2.2 on 2023-08-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0007_produto_uploaded_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='imagem',
            new_name='file',
        ),
    ]
