# Generated by Django 4.2.2 on 2023-08-23 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0008_rename_imagem_produto_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='attachment_key',
            field=models.UUIDField(default=uuid.uuid4, help_text='Used to attach the image to another object. Cannot be used to retrieve the image file.', unique=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Used to retrieve the image itself. Should not be readable until the image is attached to another object.', unique=True),
        ),
    ]
