# Generated by Django 4.2.2 on 2023-08-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0009_produto_attachment_key_produto_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='attachment_key',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='public_id',
        ),
    ]
