# Generated by Django 4.2.2 on 2023-08-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0010_remove_produto_attachment_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='uploaded_on',
        ),
        migrations.AlterField(
            model_name='produto',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=()),
        ),
    ]
