# Generated by Django 4.2.2 on 2023-08-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0012_remove_produto_file_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
