# Generated by Django 4.2.2 on 2023-08-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0014_categoria_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
