# Generated by Django 4.2.2 on 2023-09-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0015_categoria_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='rua',
        ),
    ]
