# Generated by Django 4.2.2 on 2023-09-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0016_remove_endereco_bairro_remove_endereco_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
