# Generated by Django 4.2.2 on 2023-10-02 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('padaria', '0018_alter_categoria_descricao_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='uploader.image'),
            preserve_default=False,
        ),
    ]
