# Generated by Django 4.2.2 on 2023-10-02 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('padaria', '0019_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uploader.image'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uploader.image'),
        ),
    ]
