# Generated by Django 4.2.6 on 2023-10-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0024_remove_carrinho_bairro_remove_carrinho_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='produto',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produto',
            field=models.ManyToManyField(related_name='produto', to='padaria.produto'),
        ),
    ]
