# Generated by Django 4.2.6 on 2023-10-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0025_remove_carrinho_produto_carrinho_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.IntegerField(choices=[(1, 'Unidade'), (2, 'Peso (KG)')], default=1),
        ),
    ]
