# Generated by Django 4.2.6 on 2023-10-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0026_remove_produto_descricao_produto_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
