# Generated by Django 4.2.6 on 2023-10-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0027_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
