# Generated by Django 4.2.6 on 2023-10-14 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0028_alter_produto_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
    ]
