# Generated by Django 4.2.6 on 2023-10-23 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('padaria', '0029_remove_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uploader.image'),
        ),
    ]
