# Generated by Django 4.2.6 on 2023-10-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0030_alter_produto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='imagem',
            new_name='cover',
        ),
    ]
