# Generated by Django 4.2.6 on 2023-10-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0032_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='produto',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='item',
            field=models.ManyToManyField(related_name='item', to='padaria.item'),
        ),
    ]
