# Generated by Django 4.2.6 on 2023-10-25 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0033_remove_carrinho_produto_carrinho_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endereco', to='padaria.endereco'),
        ),
    ]
