# Generated by Django 4.2.6 on 2023-12-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0035_alter_item_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinho',
            old_name='endereco',
            new_name='endereco_carrinho',
        ),
    ]
