# Generated by Django 4.2.6 on 2023-12-07 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0036_rename_endereco_carrinho_endereco_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='endereco_carrinho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='endereco', to='padaria.endereco'),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, related_name='item', to='padaria.item'),
        ),
    ]
