# Generated by Django 4.2.6 on 2023-12-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0037_alter_carrinho_endereco_carrinho_alter_carrinho_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='item',
            field=models.ManyToManyField(related_name='item', to='padaria.item'),
        ),
    ]
